import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import axios from "axios";
import { useState } from 'react'

export default function Home() {
  return (
    <>
      <Head>
        <title>TaleTeller</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@0;1&display=swap" rel="stylesheet" />
      </Head>
      <main className={styles.homeMain}>
        <Image
          src="/homeScreenBackground.png"
          alt="Dall-E generated image"
          style={{zIndex: 1, objectFit: "cover"}}
          quality={100}
          fill
        />
        <Link href="prompt" className={styles.homeButton}>
          <h2 className={styles.homeButtonText}>
            criar uma história
          </h2>
          <Image
          src="/arrow-right-green.svg"
          alt="Arrow right image"
          width={20}
          height={20}
          />
        </Link>
      </main>
    </>
  )
}
